# Uncomment this line to define a global platform for your project
#platform :ios, ‘7.0’

# ignore all warnings from all pods
inhibit_all_warnings!

xcodeproj 'COHttpClient.xcodeproj'

def all_pods
pod 'AFNetworking', '3.0.4'
end

target 'COHttpClient' do
all_pods
end

