# Uncomment this line to define a global platform for your project
platform :ios, ‘9.0’

# ignore all warnings from all pods
inhibit_all_warnings!
use_frameworks!

project 'COHttpClient.xcodeproj'

def all_pods
#pod 'AFNetworking', '3.0.4', :subspecs => ['Reachability','NSURLSession']
#pod 'AFNetworking', '~> 3.0', :source => 'https://github.com/ElfSundae/CocoaPods-Specs.git'
pod 'AFNetworking', '3.0.4', :subspecs => ['Reachability','Serialization','Security','NSURLSession']
end

target 'COHttpClient' do
all_pods

end


